### ISSUE TITLE
how to install cms ?

### ISSUE THREAD

**Issue by austindesign** [imfiroz/CMS-wordpress-CI#1]
i download cms from you.. i cant install it

**Comment by imfiroz** [comment]
Its required a database

**Comment by austindesign** [comment]
<img width="1680" alt="screen shot 2018-01-12 at 1 37 53 pm" src="https://user-images.githubusercontent.com/25316218/34862592-d7a2a71e-f79d-11e7-873b-9b82cf575474.png">
my error

**Comment by imfiroz** [comment]
Hi austindesign,

If you want to install?  
You need a structured  database, currently i am working on admin controls then after i will move to automatic database create trigger method.
But if you want to see i will send you database file(atteched 
[cms_wp_ci.zip](https://github.com/imfiroz/CMS-wordpress-CI/files/1625466/cms_wp_ci.zip)
). You just unzip it and import .sql file on MYSQL database and configure codeigniter database.php file according to your sever.
Then it will run successfully:
Use Username: firoz and Password: 1234
if you still face issue feel free to contact.

**Comment by austindesign** [comment]
im was import your database but your cms show error
<img width="1680" alt="screen shot 2018-01-12 at 5 54 28 pm" src="https://user-images.githubusercontent.com/25316218/34871888-be7f466a-f7c1-11e7-9bc7-4a07ec3ef498.png">
<img width="1680" alt="screen shot 2018-01-12 at 5 54 21 pm" src="https://user-images.githubusercontent.com/25316218/34871889-beafa97c-f7c1-11e7-9253-3f1950a44f42.png">
you can chat with me from skype:austin.mmo@gmail.com

**Comment by imfiroz** [comment]
i have correct that toady update your code with latest version

**Comment by austindesign** [comment]
i has downloaded last update , but it error

**Comment by imfiroz** [comment]
okay 

Update controller admin.php  file with this file -
[admin.zip](https://github.com/imfiroz/CMS-wordpress-CI/files/1625817/admin.zip)  unzip it first

**Comment by austindesign** [comment]
im unzip and copy to file, it login okay admin but menu admin error. and old error not fix

**Comment by austindesign** [comment]
<img width="1680" alt="screen shot 2018-01-12 at 6 17 49 pm" src="https://user-images.githubusercontent.com/25316218/34872778-e959a67a-f7c4-11e7-9131-ecdb39b75231.png">

**Comment by austindesign** [comment]
<img width="1680" alt="screen shot 2018-01-12 at 6 18 48 pm" src="https://user-images.githubusercontent.com/25316218/34872805-0ce03b9a-f7c5-11e7-9ee1-ccb83bd9b222.png">

**Comment by imfiroz** [comment]
its not a error, its a warning showing i thought you are MAMP server and i am using XAMPP Server so i am not able to see these warnings

**Comment by austindesign** [comment]
im will test xampp server

**Comment by imfiroz** [comment]
Show me this in full image so i can rectify it because i cant see it on my side 
![34872778-e959a67a-f7c4-11e7-9131-ecdb39b75231](https://user-images.githubusercontent.com/32397736/34873243-4d3d4f12-f7ba-11e7-95f2-13a28d52e305.jpg)

**Comment by austindesign** [comment]
this
<img width="1680" alt="screen shot 2018-01-12 at 6 43 26 pm" src="https://user-images.githubusercontent.com/25316218/34873649-7ecdfd2a-f7c8-11e7-88ba-26dc693d07a0.png">
